# Loaded automatically after lfwm.conf.
set border_width 2
set border_active #528AE0
set border_inactive #3B3B48
set bar_height 26
set active_opacity 0.96
set inactive_opacity 0.88
set animations true
set animation_steps 6
set animation_delay_ms 4
