set border_width 2
set border_active #528AE0
set border_inactive #3B3B48
set gap_in 8
set gap_out 12
set smart_borders true
set smart_gaps true
set modifier SUPER
set drag_modifier SUPER
set default_layout MASTER_STACK
set master_ratio 0.50
set master_count 1

ws 1 layout master_stack
ws 2 layout grid
ws 3 layout master_stack
ws 4 layout horiz

bind SUPER t exec kitty
bind SUPER b exec firefox
bind SUPER q close
bind SUPER v exec pavucontrol
bind SUPER e exec thunar
bind SUPER Right workspace_next
bind SUPER Left workspace_prev
bind SUPER Space layout_next
bind SUPER r reload
bind SUPER Escape quit

bind SUPER 1 workspace 1
bind SUPER 2 workspace 2
bind SUPER 3 workspace 3
bind SUPER 4 workspace 4
bind SUPER 5 workspace 5
bind SUPER 6 workspace 6
bind SUPER 7 workspace 7
bind SUPER 8 workspace 8
bind SUPER 9 workspace 9
bind SUPER 0 workspace 10
bind SUPER+SHIFT 1 movetows 1
bind SUPER+SHIFT 2 movetows 2
bind SUPER+SHIFT 3 movetows 3
bind SUPER+SHIFT 4 movetows 4
bind SUPER+SHIFT 5 movetows 5
bind SUPER+SHIFT 6 movetows 6
bind SUPER+SHIFT 7 movetows 7
bind SUPER+SHIFT 8 movetows 8
bind SUPER+SHIFT 9 movetows 9
bind SUPER+SHIFT 0 movetows 10

rule pavucontrol float
rule thunar float
rule firefox workspace 2

exec picom --corner-radius 10 --backend xrender --daemon || true
exec feh --bg-fill /usr/share/lfwm/wallpapers/gruvbox_wallpaper.png || xsetroot -solid '#666666'
exec dunst
